### ISSUE TITLE
Issue 1 understanding ORM

### ISSUE THREAD

**Issue by NCFindley** [NCFindley/pokemon_database#1]
I'm currently having issue using/understanding ORM find method for Stats class (pokedex.rb file) running  my tests. I'm receiving no defined method. I also have question on how to use the ORM method to be reusable when some class uses 4 variables to be initialize and other use 2 variables.

**Comment by sumeetjain** [comment]
I see two questions:

1. "I'm currently having issue using/understanding ORM find method for Stats class (pokedex.rb file) running my tests. I'm receiving no defined method."
2. "I also have question on how to use the ORM method to be reusable when some class uses 4 variables to be initialize and other use 2 variables."

Those should be two asks.

For the first one, please resubmit an `/ask` and follow the format for typing out your question: https://github.com/omahacodeschool/class-gumiho/blob/master/notes/0602-using-slash-commands.md#to-ask-questions

For the second one, please resubmit an `/ask`. Just copy/paste your question into it, and I'll reply. No need for linking to code or anything like that, since it's a conceptual question.
